/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author Albano Díez de Paulino
 */
public class Games extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Games() {
        initComponents();
        TBGames.getTableHeader().setOpaque(false);
        TBGames.getTableHeader().setBackground(new Color(102, 192, 244));
        TBGames.getTableHeader().setForeground(Color.white);
        TBGames.getTableHeader().setFont(new Font("Roboto Medium",1,14));
        
    }

 
       
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondologin = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBGames = new javax.swing.JTable();
        copyright = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        filter = new javax.swing.JButton();
        JLName = new javax.swing.JLabel();

        fondologin.setBackground(new java.awt.Color(42, 71, 94));
        fondologin.setPreferredSize(new java.awt.Dimension(700, 750));
        fondologin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(27, 40, 56));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TBGames.setBackground(new java.awt.Color(42, 71, 94));
        TBGames.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        TBGames.setForeground(new java.awt.Color(255, 255, 255));
        TBGames.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Genre", "Date Release", "Company"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TBGames.setSelectionBackground(new java.awt.Color(102, 192, 244));
        TBGames.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(TBGames);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 650, -1));

        fondologin.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 700, 490));

        copyright.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        copyright.setForeground(new java.awt.Color(255, 255, 255));
        copyright.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copyright.setText("<html>\n<body>\n© 2023 Valve Corporation. Todos los derechos reservados. <br>\nTodas las marcas registradas pertenecen a sus respectivos dueños en EE. UU. y otros países.<br>\n Todos los precios incluyen IVA (donde sea aplicable). \n</body>\n</html"); // NOI18N
        copyright.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        copyright.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                copyrightMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                copyrightMouseExited(evt);
            }
        });
        fondologin.add(copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 700, 70));

        jPanel2.setBackground(new java.awt.Color(23, 26, 33));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        filter.setBackground(new java.awt.Color(172, 213, 80));
        filter.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        filter.setForeground(new java.awt.Color(255, 255, 255));
        filter.setText("Filter");
        filter.setBorder(null);
        filter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(filter, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 180, 40));

        JLName.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        JLName.setForeground(new java.awt.Color(255, 255, 255));
        JLName.setText("Welcome elpepe");
        JLName.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(JLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 180, 40));

        fondologin.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondologin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondologin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void copyrightMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_copyrightMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_copyrightMouseEntered

    private void copyrightMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_copyrightMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_copyrightMouseExited

    public JLabel getJLName() {
        return JLName;
    }

    public void setJLName(JLabel JLName) {
        this.JLName = JLName;
    }

    public JTable getTBGames() {
        return TBGames;
    }

    public void setTBGames(JTable TBGames) {
        this.TBGames = TBGames;
    }

    public JButton getFilter() {
        return filter;
    }

    public void setFilter(JButton filter) {
        this.filter = filter;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLName;
    private javax.swing.JTable TBGames;
    private javax.swing.JLabel copyright;
    private javax.swing.JButton filter;
    private javax.swing.JPanel fondologin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
