/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.util.Iterator;
import java.util.LinkedList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import models.Game;
import models.GameDAO;

/**
 *
 * @author Albano Díez de Paulino
 */
public class Games extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Games() {
        initComponents();

        ImageIcon image = new ImageIcon("resources/signout.png");
        Image imgEscalada = image.getImage().getScaledInstance(40, 40, Image.SCALE_DEFAULT);
        ImageIcon imgFinal = new ImageIcon(imgEscalada);
        JLExit.setIcon(imgFinal);

        this.repaint();
        TBGames.getTableHeader().setOpaque(false);
        TBGames.getTableHeader().setBackground(new Color(102, 192, 244));
        TBGames.getTableHeader().setForeground(Color.white);
        TBGames.getTableHeader().setFont(new Font("Roboto Medium", 1, 14));
        jScrollPane1.getViewport().setBackground(new Color(42, 71, 94));
        DefaultTableCellRenderer dtcr = (DefaultTableCellRenderer) TBGames.getCellRenderer(1, 1);
        dtcr.setHorizontalAlignment(SwingConstants.CENTER);

    }

    private void filtrar(String nombre, String genero, String company) {

        GameDAO.leerGames();
        LinkedList<Game> lista = GameDAO.getListgame();
        DefaultTableModel modelo = (DefaultTableModel) TBGames.getModel();

        modelo.setRowCount(0);

        Iterator<Game> it = lista.iterator();
        while (it.hasNext()) {

            Game game = it.next();
            if (!(nombre.equalsIgnoreCase("Name") || nombre.isBlank())) {
                if (!(game.getNombre().toLowerCase().contains(nombre))) {
                    it.remove();
                }
            }

        }

        Iterator<Game> it2 = lista.iterator();
        while (it2.hasNext()) {

            Game game = it2.next();

            if (!(genero.equalsIgnoreCase("Genre") || genero.isBlank())) {
                if (!(game.getGenre().toLowerCase().contains(genero))) {
                    it2.remove();
                }
            }

        }

        Iterator<Game> it3 = lista.iterator();
        while (it3.hasNext()) {

            Game game = it3.next();

            if (!(company.equalsIgnoreCase("Company") || company.isBlank())) {
                if (!(game.getCompany().toLowerCase().contains(company))) {
                    it3.remove();
                }
            }

        }
        for (Game game : lista) {
            String[] row = {game.getNombre(), game.getGenre(), game.getDate(), game.getCompany(), game.getDistribution(), game.getPegi()};
            modelo.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondologin = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBGames = new javax.swing.JTable();
        info = new javax.swing.JButton();
        copyright = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        JLFName = new javax.swing.JLabel();
        JLExit = new javax.swing.JLabel();
        TFFName = new javax.swing.JTextField();
        JLName = new javax.swing.JLabel();
        TFFGenre = new javax.swing.JTextField();
        JLFGenre = new javax.swing.JLabel();
        TFFCompany = new javax.swing.JTextField();
        JLFCompany = new javax.swing.JLabel();
        filterb = new javax.swing.JButton();

        fondologin.setBackground(new java.awt.Color(42, 71, 94));
        fondologin.setPreferredSize(new java.awt.Dimension(700, 750));
        fondologin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(27, 40, 56));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TBGames.setBackground(new java.awt.Color(42, 71, 94));
        TBGames.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        TBGames.setForeground(new java.awt.Color(255, 255, 255));
        TBGames.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Genre", "Date Release", "Company", "Distribution", "PEGI"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBGames.setFocusable(false);
        TBGames.setSelectionBackground(new java.awt.Color(102, 192, 244));
        TBGames.setSelectionForeground(new java.awt.Color(255, 255, 255));
        TBGames.setShowHorizontalLines(true);
        TBGames.setShowVerticalLines(true);
        jScrollPane1.setViewportView(TBGames);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 640, 380));

        info.setBackground(new java.awt.Color(102, 192, 244));
        info.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        info.setForeground(new java.awt.Color(255, 255, 255));
        info.setText("+ Info");
        info.setActionCommand("+Info");
        info.setBorder(null);
        info.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        info.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        info.setName("info"); // NOI18N
        jPanel1.add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 160, 40));
        info.getAccessibleContext().setAccessibleName("+Info");

        fondologin.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 700, 490));

        copyright.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        copyright.setForeground(new java.awt.Color(255, 255, 255));
        copyright.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copyright.setText("<html>\n<body>\n© 2023 Valve Corporation. Todos los derechos reservados. <br>\nTodas las marcas registradas pertenecen a sus respectivos dueños en EE. UU. y otros países.<br>\n Todos los precios incluyen IVA (donde sea aplicable). \n</body>\n</html"); // NOI18N
        copyright.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        copyright.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                copyrightMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                copyrightMouseExited(evt);
            }
        });
        fondologin.add(copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 700, 70));

        jPanel2.setBackground(new java.awt.Color(23, 26, 33));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add.setBackground(new java.awt.Color(172, 213, 80));
        add.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("Add Game");
        add.setToolTipText("");
        add.setActionCommand("AddGame");
        add.setBorder(null);
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add.setName("AddGame"); // NOI18N
        jPanel2.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 160, 40));
        add.getAccessibleContext().setAccessibleName("AddGame");

        JLFName.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        JLFName.setForeground(new java.awt.Color(255, 255, 255));
        JLFName.setText("Name: ");
        JLFName.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(JLFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 40));

        JLExit.setForeground(new java.awt.Color(255, 255, 255));
        JLExit.setName("JLExit"); // NOI18N
        jPanel2.add(JLExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 40, 40));

        TFFName.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        TFFName.setForeground(new java.awt.Color(153, 153, 153));
        TFFName.setText("Name");
        TFFName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TFFNameFocusGained(evt);
            }
        });
        TFFName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFFNameKeyReleased(evt);
            }
        });
        jPanel2.add(TFFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 160, 40));

        JLName.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        JLName.setForeground(new java.awt.Color(255, 255, 255));
        JLName.setText("Welcome elpepe");
        JLName.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(JLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 130, 40));

        TFFGenre.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        TFFGenre.setForeground(new java.awt.Color(153, 153, 153));
        TFFGenre.setText("Genre");
        TFFGenre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TFFGenreFocusGained(evt);
            }
        });
        TFFGenre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFFGenreKeyReleased(evt);
            }
        });
        jPanel2.add(TFFGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 160, 40));

        JLFGenre.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        JLFGenre.setForeground(new java.awt.Color(255, 255, 255));
        JLFGenre.setText("Genre: ");
        JLFGenre.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(JLFGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 50, 40));

        TFFCompany.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        TFFCompany.setForeground(new java.awt.Color(153, 153, 153));
        TFFCompany.setText("Company");
        TFFCompany.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TFFCompanyFocusGained(evt);
            }
        });
        TFFCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFFCompanyActionPerformed(evt);
            }
        });
        TFFCompany.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFFCompanyKeyReleased(evt);
            }
        });
        jPanel2.add(TFFCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 160, 40));

        JLFCompany.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        JLFCompany.setForeground(new java.awt.Color(255, 255, 255));
        JLFCompany.setText("Company: ");
        JLFCompany.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(JLFCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 70, 40));

        filterb.setBackground(new java.awt.Color(102, 192, 244));
        filterb.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        filterb.setForeground(new java.awt.Color(255, 255, 255));
        filterb.setText("Clear");
        filterb.setBorder(null);
        filterb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        filterb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        filterb.setName("Filter"); // NOI18N
        jPanel2.add(filterb, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 160, 40));

        fondologin.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondologin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondologin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void copyrightMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_copyrightMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_copyrightMouseEntered

    private void copyrightMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_copyrightMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_copyrightMouseExited

    private void TFFCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFFCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFFCompanyActionPerformed

    private void TFFNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFFNameFocusGained
        if (TFFName.getText().equalsIgnoreCase("Name")) {
            TFFName.setText("");
            TFFName.setForeground(Color.BLACK);
        }
        if (TFFGenre.getText().isBlank()) {
            TFFGenre.setText("Genre");
            TFFGenre.setForeground(Color.GRAY);
        }
        if (TFFCompany.getText().isBlank()) {
            TFFCompany.setText("Company");
            TFFCompany.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_TFFNameFocusGained

    private void TFFGenreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFFGenreFocusGained
        if (TFFGenre.getText().equalsIgnoreCase("Genre")) {
            TFFGenre.setText("");
            TFFGenre.setForeground(Color.BLACK);
        }
        if (TFFName.getText().isBlank()) {
            TFFName.setText("Name");
            TFFName.setForeground(Color.GRAY);
        }
        if (TFFCompany.getText().isBlank()) {
            TFFCompany.setText("Company");
            TFFCompany.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_TFFGenreFocusGained

    private void TFFCompanyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFFCompanyFocusGained
        if (TFFCompany.getText().equalsIgnoreCase("Company")) {
            TFFCompany.setText("");
            TFFCompany.setForeground(Color.BLACK);
        }
        if (TFFName.getText().isBlank()) {
            TFFName.setText("Name");
            TFFName.setForeground(Color.GRAY);
        }
        if (TFFGenre.getText().isBlank()) {
            TFFGenre.setText("Genre");
            TFFGenre.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_TFFCompanyFocusGained

    private void TFFNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFFNameKeyReleased
        filtrar(TFFName.getText().toLowerCase(), TFFGenre.getText().toLowerCase(), TFFCompany.getText().toLowerCase());
    }//GEN-LAST:event_TFFNameKeyReleased

    private void TFFGenreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFFGenreKeyReleased
        filtrar(TFFName.getText().toLowerCase(), TFFGenre.getText().toLowerCase(), TFFCompany.getText().toLowerCase());
    }//GEN-LAST:event_TFFGenreKeyReleased

    private void TFFCompanyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFFCompanyKeyReleased
        filtrar(TFFName.getText().toLowerCase(), TFFGenre.getText().toLowerCase(), TFFCompany.getText().toLowerCase());
    }//GEN-LAST:event_TFFCompanyKeyReleased

    public JTable getTBGames() {
        return TBGames;
    }

    public void setTBGames(JTable TBGames) {
        this.TBGames = TBGames;
    }

    public JButton getFilterb() {
        return filterb;
    }

    public JLabel getJLExit() {
        return JLExit;
    }

    public void setJLExit(JLabel JLExit) {
        this.JLExit = JLExit;
    }

    public JLabel getJLName() {
        return JLName;
    }

    public void setJLName(JLabel JLName) {
        this.JLName = JLName;
    }

    public JTextField getTFFCompany() {
        return TFFCompany;
    }

    public void setTFFCompany(JTextField TFFCompany) {
        this.TFFCompany = TFFCompany;
    }

    public JTextField getTFFGenre() {
        return TFFGenre;
    }

    public void setTFFGenre(JTextField TFFGenre) {
        this.TFFGenre = TFFGenre;
    }

    public JTextField getTFFName() {
        return TFFName;
    }

    public void setTFFName(JTextField TFFName) {
        this.TFFName = TFFName;
    }

    public JButton getAdd() {
        return add;
    }

    public void setAdd(JButton add) {
        this.add = add;
    }

    public JButton getInfo() {
        return info;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLExit;
    private javax.swing.JLabel JLFCompany;
    private javax.swing.JLabel JLFGenre;
    private javax.swing.JLabel JLFName;
    private javax.swing.JLabel JLName;
    private javax.swing.JTable TBGames;
    private javax.swing.JTextField TFFCompany;
    private javax.swing.JTextField TFFGenre;
    private javax.swing.JTextField TFFName;
    private javax.swing.JButton add;
    private javax.swing.JLabel copyright;
    private javax.swing.JButton filterb;
    private javax.swing.JPanel fondologin;
    private javax.swing.JButton info;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
