/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author carra
 */
public class GameView extends javax.swing.JDialog {

    /**
     * Creates new form Add
     */
    public GameView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        copyright = new javax.swing.JLabel();
        formulario = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Description = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Price = new javax.swing.JLabel();
        version1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        genre = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        company = new javax.swing.JLabel();
        pegi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Module Add Game");

        fondo.setBackground(new java.awt.Color(42, 71, 94));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        copyright.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        copyright.setForeground(new java.awt.Color(255, 255, 255));
        copyright.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copyright.setText("<html>\n<body>\n© 2023 Valve Corporation. Todos los derechos reservados. <br>\nTodas las marcas registradas pertenecen a sus respectivos dueños en EE. UU. y otros países.<br>\n Todos los precios incluyen IVA (donde sea aplicable). \n</body>\n</html"); // NOI18N
        copyright.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        copyright.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                copyrightMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                copyrightMouseExited(evt);
            }
        });
        fondo.add(copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 700, 70));

        formulario.setBackground(new java.awt.Color(27, 40, 56));
        formulario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(42, 71, 94));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Description.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        Description.setForeground(new java.awt.Color(255, 255, 255));
        Description.setText("Description");
        Description.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(Description, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 190, 180));
        jPanel2.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 380, 180));

        formulario.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 630, 220));

        jPanel3.setBackground(new java.awt.Color(42, 71, 94));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Price.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        Price.setForeground(new java.awt.Color(255, 255, 255));
        Price.setText("Price");
        jPanel3.add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 190, 40));

        version1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        version1.setForeground(new java.awt.Color(255, 255, 255));
        version1.setText("Version");
        jPanel3.add(version1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 380, 40));

        formulario.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 630, 80));

        fondo.add(formulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 700, 480));

        jPanel1.setBackground(new java.awt.Color(23, 26, 33));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        genre.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        genre.setForeground(new java.awt.Color(255, 255, 255));
        genre.setText("Genre");
        jPanel1.add(genre, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 110, 60));

        title.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Title");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 390, 60));

        company.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        company.setForeground(new java.awt.Color(255, 255, 255));
        company.setText("Company");
        jPanel1.add(company, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 390, 40));

        pegi.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        pegi.setForeground(new java.awt.Color(255, 255, 255));
        pegi.setText("Pegi");
        jPanel1.add(pegi, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 110, 40));

        fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void copyrightMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_copyrightMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_copyrightMouseEntered

    private void copyrightMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_copyrightMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_copyrightMouseExited

    public JLabel getDescription() {
        return Description;
    }

    public void setDescription(JLabel Description) {
        this.Description = Description;
    }

    public JLabel getPrice() {
        return Price;
    }

    public void setPrice(JLabel Price) {
        this.Price = Price;
    }

    public JLabel gettitle() {
        return title;
    }

    public void setTitle(JLabel Title) {
        this.title = Title;
    }

    public JLabel getCompany() {
        return company;
    }

    public void setCompany(JLabel company) {
        this.company = company;
    }

    public JLabel getGenre() {
        return genre;
    }

    public void setGenre(JLabel genre) {
        this.genre = genre;
    }

    public JLabel getImg() {
        return img;
    }

    public void setImg(JLabel img) {
        this.img = img;
    }

    public JLabel getPegi() {
        return pegi;
    }

    public void setPegi(JLabel pegi) {
        this.pegi = pegi;
    }

    public JLabel getVersion1() {
        return version1;
    }

    public void setVersion1(JLabel version1) {
        this.version1 = version1;
    }
    
    public void setImagen(String ruta){
         ImageIcon image = new ImageIcon(ruta);
        Image imgEscalada = image.getImage().getScaledInstance(380, 180, Image.SCALE_DEFAULT);
        ImageIcon imgFinal = new ImageIcon(imgEscalada);
        img.setIcon(imgFinal);
        this.repaint();
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Description;
    private javax.swing.JLabel Price;
    private javax.swing.JLabel company;
    private javax.swing.JLabel copyright;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel formulario;
    private javax.swing.JLabel genre;
    private javax.swing.JLabel img;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel pegi;
    private javax.swing.JLabel title;
    private javax.swing.JLabel version1;
    // End of variables declaration//GEN-END:variables
}
